/**
 * Task icon options using Lucide React Native icons
 * Essential icons for common tasks and chores
 */
export const TASK_ICON_OPTIONS = [
  { name: 'Task', component: 'ListTodo' },
  { name: 'CheckCircle', component: 'CheckCircle' },
  { name: 'Trash', component: 'Trash2' },
  { name: 'Utensils', component: 'UtensilsCrossed' },
  { name: 'Shopping Cart', component: 'ShoppingCart' },
  { name: 'Shopping Bag', component: 'ShoppingBag' },
  { name: 'Droplet', component: 'Droplet' },
  { name: 'Shirt', component: 'Shirt' },
  { name: 'Car', component: 'Car' },
  { name: 'Book', component: 'BookOpen' },
  { name: 'Briefcase', component: 'Briefcase' },
  { name: 'Dumbbell', component: 'Dumbbell' },
  { name: 'Smartphone', component: 'Smartphone' },
  { name: 'Laptop', component: 'Laptop' },
  { name: 'Music', component: 'Music' },
  { name: 'Film', component: 'Film' },
  { name: 'Coffee', component: 'Coffee' },
  { name: 'Sparkles', component: 'Sparkles' },
  { name: 'Wind', component: 'Wind' },
  { name: 'Bed', component: 'BedDouble' },
  { name: 'Bath', component: 'Bath' },
  { name: 'Paintbrush', component: 'Paintbrush' },
  { name: 'Wand2', component: 'Wand2' },
  { name: 'Microwave', component: 'Microwave' },
  { name: 'Refrigerator', component: 'Refrigerator' },
  { name: 'Zap', component: 'Zap' },
  { name: 'Flower2', component: 'Flower2' },
  { name: 'Mail', component: 'Mail' },
  { name: 'Pill', component: 'Pill' },
  { name: 'Baby', component: 'Baby' },
  { name: 'Dog', component: 'Dog' },
  { name: 'Cat', component: 'Cat' },
  { name: 'Fuel', component: 'Fuel' },
  { name: 'Wrench', component: 'Wrench' },
  { name: 'Leaf', component: 'Leaf' },
  { name: 'Globe', component: 'Globe' },
  { name: 'Camera', component: 'Camera' },
  { name: 'Calendar', component: 'Calendar' },
  { name: 'Clock', component: 'Clock' },
  { name: 'Home', component: 'Home' },
  { name: 'Key', component: 'Key' },
  { name: 'Lock', component: 'Lock' },
  { name: 'Bell', component: 'Bell' },
  { name: 'Heart', component: 'Heart' },
  { name: 'Star', component: 'Star' },
  { name: 'ChefHat', component: 'ChefHat' },
  { name: 'Flame', component: 'Flame' },
  { name: 'Recycle', component: 'Recycle' },
  { name: 'Sprout', component: 'Sprout' },
  { name: 'DoorOpen', component: 'DoorOpen' },
  { name: 'Square', component: 'Square' },
  { name: 'Lightbulb', component: 'Lightbulb' },
  { name: 'Plug', component: 'Plug' },
  { name: 'Battery', component: 'Battery' },
  { name: 'Wifi', component: 'Wifi' },
  { name: 'Speaker', component: 'Speaker' },
  { name: 'Headphones', component: 'Headphones' },
  { name: 'Mic', component: 'Mic' },
  { name: 'Gamepad2', component: 'Gamepad2' },
  { name: 'Monitor', component: 'Monitor' },
  { name: 'Printer', component: 'Printer' },
  { name: 'Folder', component: 'Folder' },
  { name: 'File', component: 'File' },
  { name: 'FileText', component: 'FileText' },
  { name: 'Notebook', component: 'Notebook' },
  { name: 'AlarmClock', component: 'AlarmClock' },
  { name: 'Timer', component: 'Timer' },
  { name: 'Hourglass', component: 'Hourglass' },
  { name: 'Watch', component: 'Watch' },
  { name: 'Users', component: 'Users' },
  { name: 'CheckSquare', component: 'CheckSquare' },
  { name: 'StickyNote', component: 'StickyNote' },
  { name: 'Package', component: 'Package' },
  { name: 'Box', component: 'Box' },
  { name: 'Tag', component: 'Tag' },
  { name: 'MapPin', component: 'MapPin' },
  { name: 'Paperclip', component: 'Paperclip' },
  { name: 'Table', component: 'Table' },
  { name: 'Circle', component: 'Circle' },
  { name: 'RectangleHorizontal', component: 'RectangleHorizontal' },
  { name: 'Trees', component: 'Trees' },
  { name: 'Anchor', component: 'Anchor' },
  { name: 'Compass', component: 'Compass' },
  { name: 'Map', component: 'Map' },
] as const;

export type TaskIconName = typeof TASK_ICON_OPTIONS[number]['component'];

/**
 * Member icon options using Lucide React Native icons
 * User/person-related icons for member avatars
 */
export const MEMBER_ICON_OPTIONS = [
  { name: 'User', component: 'User' },
  { name: 'User Circle', component: 'UserCircle' },
  { name: 'Users', component: 'Users' },
  { name: 'Smile', component: 'Smile' },
  { name: 'Heart', component: 'Heart' },
  { name: 'Star', component: 'Star' },
  { name: 'Crown', component: 'Crown' },
  { name: 'Zap', component: 'Zap' },
  { name: 'Trophy', component: 'Trophy' },
  { name: 'Award', component: 'Award' },
  { name: 'Gift', component: 'Gift' },
  { name: 'Sun', component: 'Sun' },
  { name: 'Moon', component: 'Moon' },
  { name: 'Flower', component: 'Flower' },
  { name: 'Leaf', component: 'Leaf' },
  { name: 'Sparkles', component: 'Sparkles' },
] as const;

export type MemberIconName = typeof MEMBER_ICON_OPTIONS[number]['component'];
